# -*- coding: utf-8 -*-
"""FA2 GC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZV-9oY-82JTIAvJsfpco2hP9ZXLecR3y
"""

# =============================================================================
# FA-2: ATM Intelligence Demand Forecasting with Data Mining
# FinTrust Bank Ltd. — Building Actionable Insights & Interactive Python Script
# =============================================================================
# HOW TO RUN:
#   1. Upload this script and the dataset CSV to Google Colab (or place in the
#      same folder in your IDE).
#   2. Make sure the CSV is named: atm_cash_management_dataset.csv
#   3. Run all cells / execute the script.
#   4. Stage 6 is interactive — follow the prompts in the terminal.
# =============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.ensemble import IsolationForest

# ─────────────────────────────────────────────────────────────────────────────
# LOAD DATASET
# ─────────────────────────────────────────────────────────────────────────────
df = pd.read_csv("atm_cash_management_dataset.csv", parse_dates=["Date"])
print("✅ Dataset loaded:", df.shape)
print(df.head())

sns.set_theme(style="whitegrid")


# =============================================================================
# STAGE 3 — EXPLORATORY DATA ANALYSIS (EDA)
# =============================================================================
print("\n" + "="*60)
print("STAGE 3: Exploratory Data Analysis (EDA)")
print("="*60)

# ── 3.1 Distribution Analysis ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("3.1 Distribution of Withdrawals & Deposits", fontsize=14, fontweight="bold")

axes[0].hist(df["Total_Withdrawals"], bins=30, color="#4C72B0", edgecolor="white")
axes[0].set_title("Total Withdrawals"); axes[0].set_xlabel("Amount"); axes[0].set_ylabel("Frequency")

axes[1].hist(df["Total_Deposits"], bins=30, color="#DD8452", edgecolor="white")
axes[1].set_title("Total Deposits"); axes[1].set_xlabel("Amount"); axes[1].set_ylabel("Frequency")

plt.tight_layout(); plt.savefig("3_1_distribution.png", dpi=100); plt.show()
print("📌 Observation: Withdrawals range ~20K–90K with a roughly uniform distribution. Deposits are lower and right-skewed — ATMs dispense more than they receive.")


# ── 3.2 Box Plots for Outliers ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("3.2 Box Plots – Outlier Detection", fontsize=14, fontweight="bold")

sns.boxplot(y=df["Total_Withdrawals"], ax=axes[0], color="#4C72B0")
axes[0].set_title("Total Withdrawals")

sns.boxplot(y=df["Total_Deposits"], ax=axes[1], color="#DD8452")
axes[1].set_title("Total Deposits")

plt.tight_layout(); plt.savefig("3_2_boxplots.png", dpi=100); plt.show()
print("📌 Observation: A few high-value outliers exist in withdrawals — likely holiday or event-driven spikes. Deposits have a tighter range with fewer extremes.")


# ── 3.3 Time-Based Trends ─────────────────────────────────────────────────
# Line chart of withdrawals over time
daily = df.groupby("Date")["Total_Withdrawals"].sum().reset_index()
plt.figure(figsize=(14, 5))
plt.plot(daily["Date"], daily["Total_Withdrawals"], color="#4C72B0", linewidth=0.8)
plt.title("3.3a Total Withdrawals Over Time", fontsize=14, fontweight="bold")
plt.xlabel("Date"); plt.ylabel("Total Withdrawals")
plt.tight_layout(); plt.savefig("3_3a_time_trend.png", dpi=100); plt.show()
print("📌 Observation: Withdrawals remain stable over time with periodic spikes, suggesting recurring high-demand events like paydays or public holidays.")

# Bar plot by Day of Week
day_order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
day_avg = df.groupby("Day_of_Week")["Total_Withdrawals"].mean().reindex(day_order)
plt.figure(figsize=(10, 5))
day_avg.plot(kind="bar", color="#4C72B0", edgecolor="white")
plt.title("3.3b Average Withdrawals by Day of Week", fontsize=14, fontweight="bold")
plt.xlabel("Day"); plt.ylabel("Avg Withdrawals"); plt.xticks(rotation=45)
plt.tight_layout(); plt.savefig("3_3b_day_of_week.png", dpi=100); plt.show()
print("📌 Observation: Withdrawals are fairly consistent across weekdays. Slight increases on certain days may reflect salary-related patterns.")

# Bar plot by Time of Day
time_avg = df.groupby("Time_of_Day")["Total_Withdrawals"].mean()
plt.figure(figsize=(8, 5))
time_avg.plot(kind="bar", color="#55A868", edgecolor="white")
plt.title("3.3c Average Withdrawals by Time of Day", fontsize=14, fontweight="bold")
plt.xlabel("Time of Day"); plt.ylabel("Avg Withdrawals"); plt.xticks(rotation=0)
plt.tight_layout(); plt.savefig("3_3c_time_of_day.png", dpi=100); plt.show()
print("📌 Observation: Morning and Evening show the highest withdrawal activity, peaking during commute hours.")


# ── 3.4 Holiday & Event Impact ────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("3.4 Impact of Holidays & Special Events on Withdrawals", fontsize=14, fontweight="bold")

df.groupby("Holiday_Flag")["Total_Withdrawals"].mean().plot(
    kind="bar", ax=axes[0], color=["#4C72B0","#DD8452"], edgecolor="white")
axes[0].set_title("Holiday Flag"); axes[0].set_xticklabels(["No Holiday","Holiday"], rotation=0)

df.groupby("Special_Event_Flag")["Total_Withdrawals"].mean().plot(
    kind="bar", ax=axes[1], color=["#4C72B0","#55A868"], edgecolor="white")
axes[1].set_title("Special Event Flag"); axes[1].set_xticklabels(["No Event","Special Event"], rotation=0)

plt.tight_layout(); plt.savefig("3_4_holiday_event.png", dpi=100); plt.show()
print("📌 Observation: ATMs see noticeably higher withdrawals on holidays and special event days — external calendar events are key demand drivers.")


# ── 3.5 External Factors ─────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("3.5 Impact of Weather & Competitor ATMs", fontsize=14, fontweight="bold")

sns.boxplot(x="Weather_Condition", y="Total_Withdrawals", data=df,
            ax=axes[0], palette="Set2", hue="Weather_Condition", legend=False)
axes[0].set_title("Withdrawals by Weather Condition")

sns.boxplot(x="Nearby_Competitor_ATMs", y="Total_Withdrawals", data=df,
            ax=axes[1], palette="Blues", hue="Nearby_Competitor_ATMs", legend=False)
axes[1].set_title("Withdrawals vs Competitor ATMs")

plt.tight_layout(); plt.savefig("3_5_external_factors.png", dpi=100); plt.show()
print("📌 Observation: Rainy weather slightly reduces withdrawal activity. ATMs with fewer competitors attract more withdrawals.")


# ── 3.6 Relationship Analysis ─────────────────────────────────────────────
# Scatter plot
plt.figure(figsize=(8, 5))
plt.scatter(df["Previous_Day_Cash_Level"], df["Cash_Demand_Next_Day"],
            alpha=0.3, color="#4C72B0", edgecolors="none")
plt.title("3.6a Previous Day Cash Level vs Next Day Cash Demand", fontsize=14, fontweight="bold")
plt.xlabel("Previous Day Cash Level"); plt.ylabel("Cash Demand Next Day")
plt.tight_layout(); plt.savefig("3_6a_scatter.png", dpi=100); plt.show()
print("📌 Observation: No strong linear relationship — demand is driven more by external events than stock levels.")

# Correlation heatmap
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
corr = df[numeric_cols].corr()
plt.figure(figsize=(10, 7))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.5)
plt.title("3.6b Correlation Heatmap of Numeric Features", fontsize=14, fontweight="bold")
plt.tight_layout(); plt.savefig("3_6b_heatmap.png", dpi=100); plt.show()
print("📌 Observation: Total_Withdrawals has moderate positive correlation with Cash_Demand_Next_Day. Holiday/event flags show mild positive correlations with withdrawals.")


# =============================================================================
# STAGE 4 — CLUSTERING ANALYSIS
# =============================================================================
print("\n" + "="*60)
print("STAGE 4: Clustering Analysis of ATMs")
print("="*60)

# Encode categorical Location_Type for clustering
le = LabelEncoder()
df["Location_Type_Enc"] = le.fit_transform(df["Location_Type"])

# Select and standardize features
cluster_features = ["Total_Withdrawals", "Total_Deposits", "Location_Type_Enc", "Nearby_Competitor_ATMs"]
X = df[cluster_features].copy()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ── Elbow Method & Silhouette Scores ────────────────────────────────────
K_range = range(2, 11)
inertia, sil_scores = [], []
for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_scaled)
    inertia.append(km.inertia_)
    sil_scores.append(silhouette_score(X_scaled, labels))

plt.figure(figsize=(8, 5))
plt.plot(K_range, inertia, marker="o", color="#4C72B0")
plt.title("4.1 Elbow Method – Optimal Number of Clusters", fontsize=14, fontweight="bold")
plt.xlabel("Number of Clusters (K)"); plt.ylabel("Inertia")
plt.tight_layout(); plt.savefig("4_1_elbow.png", dpi=100); plt.show()
print("📌 Observation: The elbow identifies where adding more clusters gives diminishing improvement.")

best_k = list(K_range)[np.argmax(sil_scores)]
print(f"✅ Best K by Silhouette Score: {best_k} (score: {max(sil_scores):.3f})")

plt.figure(figsize=(8, 5))
plt.plot(K_range, sil_scores, marker="s", color="#DD8452")
plt.title("4.2 Silhouette Scores for Each K", fontsize=14, fontweight="bold")
plt.xlabel("Number of Clusters (K)"); plt.ylabel("Silhouette Score")
plt.tight_layout(); plt.savefig("4_2_silhouette.png", dpi=100); plt.show()


# ── Apply K-Means with Best K ────────────────────────────────────────────
kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
df["Cluster"] = kmeans.fit_predict(X_scaled)

# Label clusters based on average withdrawal (low → high)
cluster_means = df.groupby("Cluster")["Total_Withdrawals"].mean().sort_values()
levels = ["Very Low","Low","Medium-Low","Medium","Medium-High","High","Very High","Extreme"]
cluster_labels = {cid: levels[min(i, len(levels)-1)] + " Demand ATMs"
                  for i, (cid, _) in enumerate(cluster_means.items())}
df["Cluster_Label"] = df["Cluster"].map(cluster_labels)

print("\n── Cluster Summary ────────────────────────────────────────────────")
print(df.groupby("Cluster_Label")[["Total_Withdrawals","Total_Deposits","Nearby_Competitor_ATMs"]].mean().round(0))

# ── Visualize Clusters ───────────────────────────────────────────────────
palette = sns.color_palette("tab10", best_k)
plt.figure(figsize=(12, 6))
for cluster_id, label in cluster_labels.items():
    subset = df[df["Cluster"] == cluster_id]
    plt.scatter(subset["Total_Withdrawals"], subset["Total_Deposits"],
                label=label, alpha=0.4, s=30, color=palette[cluster_id])
plt.title("4.3 ATM Clusters: Withdrawals vs Deposits", fontsize=14, fontweight="bold")
plt.xlabel("Total Withdrawals"); plt.ylabel("Total Deposits")
plt.legend(loc="upper right", fontsize=8)
plt.tight_layout(); plt.savefig("4_3_clusters.png", dpi=100); plt.show()
print("📌 Observation: Clusters show distinct demand bands — high-demand ATMs should be prioritized for more frequent cash replenishment.")

df["Cluster_Label"].value_counts().plot(kind="bar", color="steelblue", edgecolor="white")
plt.title("4.4 Number of Records per Cluster", fontsize=14, fontweight="bold")
plt.xlabel("Cluster"); plt.ylabel("Count"); plt.xticks(rotation=30)
plt.tight_layout(); plt.savefig("4_4_cluster_counts.png", dpi=100); plt.show()


# =============================================================================
# STAGE 5 — ANOMALY DETECTION
# =============================================================================
print("\n" + "="*60)
print("STAGE 5: Anomaly Detection on Holidays/Events")
print("="*60)

# ── 5.1 Compare Holiday vs Normal Days ──────────────────────────────────
plt.figure(figsize=(14, 5))
plt.hist(df[df["Holiday_Flag"]==0]["Total_Withdrawals"], bins=30,
         alpha=0.6, label="Normal Days", color="#4C72B0", edgecolor="white")
plt.hist(df[df["Holiday_Flag"]==1]["Total_Withdrawals"], bins=30,
         alpha=0.7, label="Holiday Days", color="#DD8452", edgecolor="white")
plt.title("5.1 Withdrawal Distribution: Holiday vs Normal Days", fontsize=14, fontweight="bold")
plt.xlabel("Total Withdrawals"); plt.ylabel("Frequency")
plt.legend(); plt.tight_layout(); plt.savefig("5_1_holiday_vs_normal.png", dpi=100); plt.show()
print("📌 Observation: Holiday days show a shifted distribution toward higher withdrawals, confirming elevated demand.")

# ── 5.2 Z-Score Anomaly Detection ───────────────────────────────────────
df["Z_Score"] = np.abs(stats.zscore(df["Total_Withdrawals"]))
df["Anomaly_ZScore"] = df["Z_Score"] > 2.5
print(f"✅ Z-Score Anomalies detected: {df['Anomaly_ZScore'].sum()}")

# ── 5.3 IQR Anomaly Detection ─────────────────────────────────────────────
Q1 = df["Total_Withdrawals"].quantile(0.25)
Q3 = df["Total_Withdrawals"].quantile(0.75)
IQR_val = Q3 - Q1
df["Anomaly_IQR"] = (df["Total_Withdrawals"] < Q1 - 1.5*IQR_val) | (df["Total_Withdrawals"] > Q3 + 1.5*IQR_val)
print(f"✅ IQR Anomalies detected: {df['Anomaly_IQR'].sum()}")

# ── 5.4 Isolation Forest ─────────────────────────────────────────────────
iso = IsolationForest(contamination=0.05, random_state=42)
df["Anomaly_IF"] = iso.fit_predict(df[["Total_Withdrawals"]]) == -1
print(f"✅ Isolation Forest Anomalies detected: {df['Anomaly_IF'].sum()}")

# ── 5.5 Visualize Anomalies Over Time ─────────────────────────────────
df_sorted = df.sort_values("Date")
normal_pts  = df_sorted[df_sorted["Anomaly_IF"] == False]
anomaly_pts = df_sorted[df_sorted["Anomaly_IF"] == True]

plt.figure(figsize=(14, 5))
plt.scatter(normal_pts["Date"],  normal_pts["Total_Withdrawals"],
            alpha=0.3, s=10, color="#4C72B0", label="Normal")
plt.scatter(anomaly_pts["Date"], anomaly_pts["Total_Withdrawals"],
            s=40, color="#DD8452", label="Anomaly (Isolation Forest)", zorder=5)
plt.title("5.5 Anomaly Detection – Withdrawals Over Time", fontsize=14, fontweight="bold")
plt.xlabel("Date"); plt.ylabel("Total Withdrawals")
plt.legend(); plt.tight_layout(); plt.savefig("5_5_anomalies_time.png", dpi=100); plt.show()
print("📌 Observation: Anomalies (orange) coincide with high-withdrawal periods — strong candidates for event-driven demand spikes.")

# ── 5.6 Anomalies on Holiday vs Normal ──────────────────────────────────
anomaly_holiday = df[df["Anomaly_IF"]==True]["Holiday_Flag"].value_counts().reindex([0,1], fill_value=0)
anomaly_holiday.index = ["Normal Days", "Holiday Days"]
anomaly_holiday.plot(kind="bar", color=["#4C72B0","#DD8452"], edgecolor="white")
plt.title("5.6 Anomalies: Holiday vs Normal Days", fontsize=14, fontweight="bold")
plt.ylabel("Anomaly Count"); plt.xticks(rotation=0)
plt.tight_layout(); plt.savefig("5_6_anomaly_holiday.png", dpi=100); plt.show()
print("📌 Observation: Higher proportion of anomalies on holiday days — holidays are a key trigger for unusual withdrawal behavior.")


# =============================================================================
# STAGE 6 — INTERACTIVE ATM CASH DEMAND PLANNER
# =============================================================================
print("\n" + "="*60)
print("STAGE 6: Interactive ATM Cash Demand Planner")
print("="*60)

def show_options():
    """Print available filter values."""
    print("\n── Available Filter Values ─────────────────────────────────")
    print(f"  Day of Week   : {sorted(df['Day_of_Week'].unique())}")
    print(f"  Time of Day   : {sorted(df['Time_of_Day'].unique())}")
    print(f"  Location Type : {sorted(df['Location_Type'].unique())}")
    print("────────────────────────────────────────────────────────────\n")

def interactive_planner():
    """Filter ATM data interactively and display cluster + anomaly insights."""

    print("\n🏧  Welcome to the FinTrust ATM Interactive Demand Planner  🏧")
    print("Filter by Day, Time, and Location to explore demand insights.")
    print("Type 'exit' at any prompt to quit.\n")

    while True:
        show_options()
        day  = input("  Filter by Day of Week   (Enter to skip): ").strip().capitalize()
        time = input("  Filter by Time of Day   (Enter to skip): ").strip().capitalize()
        loc  = input("  Filter by Location Type (Enter to skip): ").strip().capitalize()

        if "Exit" in [day, time, loc]:
            print("\n👋 Exiting the planner. Goodbye!")
            break

        # Apply filters
        filtered = df.copy()
        if day:
            if day in df["Day_of_Week"].values:
                filtered = filtered[filtered["Day_of_Week"] == day]
            else:
                print(f"  ⚠️  '{day}' not recognized — skipping Day filter.")
        if time:
            if time in df["Time_of_Day"].values:
                filtered = filtered[filtered["Time_of_Day"] == time]
            else:
                print(f"  ⚠️  '{time}' not recognized — skipping Time filter.")
        if loc:
            if loc in df["Location_Type"].values:
                filtered = filtered[filtered["Location_Type"] == loc]
            else:
                print(f"  ⚠️  '{loc}' not recognized — skipping Location filter.")

        if filtered.empty:
            print("  ❌ No data matches these filters. Try different values.\n")
            continue

        print(f"\n✅ {len(filtered)} records matched.\n")

        # Summary statistics
        print("── Summary Statistics ─────────────────────────────────────────")
        print(filtered[["Total_Withdrawals","Total_Deposits","Cash_Demand_Next_Day"]].describe().round(0))

        # Cluster breakdown
        print("\n── Cluster Distribution ───────────────────────────────────────")
        print(filtered["Cluster_Label"].value_counts().to_string())

        # Anomaly count
        n_anom = filtered["Anomaly_IF"].sum()
        print(f"\n── Anomalies Detected : {n_anom} ({n_anom/len(filtered)*100:.1f}% of filtered data)")

        # Plot dashboard
        filter_str = f"Day={day or 'All'} | Time={time or 'All'} | Loc={loc or 'All'}"
        fig, axes = plt.subplots(1, 3, figsize=(16, 5))
        fig.suptitle(f"Interactive Planner – {filter_str}", fontsize=12, fontweight="bold")

        # Histogram
        axes[0].hist(filtered["Total_Withdrawals"], bins=20, color="#4C72B0", edgecolor="white")
        axes[0].set_title("Withdrawal Distribution")
        axes[0].set_xlabel("Withdrawals"); axes[0].set_ylabel("Frequency")

        # Cluster bar chart
        filtered["Cluster_Label"].value_counts().plot(kind="bar", ax=axes[1],
                                                       color="steelblue", edgecolor="white")
        axes[1].set_title("Cluster Distribution")
        axes[1].set_xlabel("Cluster"); axes[1].set_ylabel("Count")
        axes[1].tick_params(axis="x", rotation=30)

        # Anomaly scatter
        fn = filtered[filtered["Anomaly_IF"] == False]
        fa = filtered[filtered["Anomaly_IF"] == True]
        axes[2].scatter(fn["Previous_Day_Cash_Level"], fn["Total_Withdrawals"],
                        alpha=0.4, s=15, color="#4C72B0", label="Normal")
        axes[2].scatter(fa["Previous_Day_Cash_Level"], fa["Total_Withdrawals"],
                        s=40, color="#DD8452", label="Anomaly", zorder=5)
        axes[2].set_title("Anomalies in Filtered Data")
        axes[2].set_xlabel("Prev Day Cash Level"); axes[2].set_ylabel("Total Withdrawals")
        axes[2].legend()

        plt.tight_layout()
        plt.savefig("planner_output.png", dpi=100); plt.show()

        again = input("\n🔄 Run another filter? (yes / no): ").strip().lower()
        if again != "yes":
            print("\n👋 Thank you for using the ATM Demand Planner!")
            break


# Run the interactive planner
interactive_planner()


print("\n" + "="*60)
print("✅ FA-2 Complete — All Stages Executed Successfully!")
print("="*60)

from google.colab import drive
drive.mount('/content/drive')